[package]
name = "statefun-protos"
version = "0.1.0"
authors = ["Aljoscha Krettek <aljoscha.krettek@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
prost = "0.6"
prost-types = "0.6"

[build-dependencies]
prost-build = { version = "0.6" }
