[package]
name = "statefun-scratch-protos"
version = "0.1.0"
authors = ["Aljoscha Krettek <aljoscha.krettek@gmail.com>"]
edition = "2018"

[dependencies]
protobuf = "2.15"

[build-dependencies]
protoc-rust = "2.15"
glob = "0.3"
