[workspace]
members = [
    "statefun-proto",
    "statefun-sdk",
    "statefun-greeter-example",
    "statefun-greeter-example-proto",
    "statefun-advanced-example",
    "statefun-greeter-example-kafka",
]
